package com.sahooexpress.models;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name="shipping_info")
@Setter
@Getter
public class ShippingInfo {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	private Long orderId;
	
	private String trackingNumber; // AutoGenerated
	private String shippingMethod; // Standard,Next-Day
	private LocalDateTime shippedAt;
	
	private LocalDateTime deliveryDate;
	private String status; // SHIPPED,IN_TRANSIT,DELIVERED
	private String carrier; // FedEx,UPS,DHL,ShadowFx
	
	

}
